export default {
	SEARCH_SONGS: "SEARCH_SONGS",
	SEARCH_VIDEOS: "SEARCH_VIDEOS",
	SET_SEARCH_TERM: "SET_SEARCH_TERM",
	SET_VIDEO_PLAYER: "SET_VIDEO_PLAYER",
	SET_SONG_DURATION: "SET_SONG_DURATION",
	SET_RANDOM_SONG: "SET_RANDOM_SONG",
	SET_PREVIOUS_INDEX: "SET_PREVIOUS_INDEX",
}