export default {
	SEARCH_SONGS: "SEARCH_SONGS",
	SEARCH_VIDEOS: "SEARCH_VIDEOS",

	SET_SEARCH_TERM: "SET_SEARCH_TERM",
	SET_VIDEO_PLAYER: "SET_VIDEO_PLAYER",

	SET_SONG_DURATION: "SET_SONG_DURATION",

	SET_RANDOM_SONG: "SET_RANDOM_SONG",
	SET_RANDOM_VIDEO: "SET_RANDOM_VIDEO",

	SET_VIDEO_INDEX: "SET_VIDEO_INDEX",
	SET_SONG_INDEX: "SET_SONG_INDEX",

	SET_SONG_STATE: "SET_SONG_STATE",
	SET_VIDEO_STATE: "SET_VIDEO_STATE",

	SAME_SEARCH_TRIGGERED: "SAME_SEARCH_TRIGGERED"
}